### ISSUE TITLE
Template files have the wrong file type

### ISSUE THREAD

**Issue by theswygue** [parmstro/ACMExport#6]
All this files should have the .yml and not .j2

- credential_ACM_vault.yml.j2
- credential_default.yml.j2
- credential_tower_github.yml.j2
- project_ACM.yml.j2

**Comment by parmstro** [comment]
Hi Roderique, If you look at the Export file, it creates any of the files that have variables as templates. When you call ImportConfig.yml the first play templates the files and using the vaulted secrets and saves them as .yml files. ImportConfig.yml is looking for source template files with a .j2 extension.

**Comment by parmstro** [comment]
The .yml files have been removed and .j2 files remain. The code generates the appropriate yml files at run time from the jinja2 templates.
