### ISSUE TITLE
acm_project_url var needs to be enclosed in double quotes

### ISSUE THREAD

**Issue by theswygue** [parmstro/ACMExport#8]
```
grep 'acm_project_url' backup/*
backup/project_ACM.yml:  scm_url: '{{ acm_project_url }}'
```

**Comment by theswygue** [comment]
Ok it seems the real issue here is that should be converted from a template so the the var acm_project_url gets processed.

or it may just be can the automation controller needs to be setup to pull content from Automation Hub.

```
TASK [fetch galaxy collections from collections/requirements.(yml/yaml)] *******
failed: [localhost] (item=/var/lib/awx/projects/_8__automatingcontentmanagement/collections/requirements.yml) => {"ansible_loop_var": "item", "changed": false, "cmd": ["ansible-galaxy", "collection", "install", "-r", "/var/lib/awx/projects/_8__automatingcontentmanagement/collections/requirements.yml", "--collections-path", "/var/lib/awx/projects/.__awx_cache/_8__automatingcontentmanagement/stage/requirements_collections"], "delta": "0:00:02.032366", "end": "2022-01-08 19:28:38.509192", "item": "/var/lib/awx/projects/_8__automatingcontentmanagement/collections/requirements.yml", "msg": "non-zero return code", "rc": 1, "start": "2022-01-08 19:28:36.476826", "stderr": "ERROR! Failed to resolve the requested dependencies map. Could not satisfy the following requirements:\n* redhat.satellite:* (direct request)", "stderr_lines": ["ERROR! Failed to resolve the requested dependencies map. Could not satisfy the following requirements:", "* redhat.satellite:* (direct request)"], "stdout": "Starting galaxy colle…
```

1. Create a Galaxy Credentials with the following info
  * automation_hub: https://console.redhat.com/api/automation-hub/
  * automation_hub_auth_url: https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
  * automation_hub_user_token: ""
2. Add the credentials to the Organization, in this case it's the default ORG

**Comment by parmstro** [comment]
This is was due to the fact that ImportConfig.yml did not loop over the projects in the template_asset_files.yml include. This is fixed in [commit 6d885c](https://github.com/parmstro/ACMExport/commit/6d885c458b6f9eb97308f47b023527a9eb973ed0)
